# Generated by Django 4.0.2 on 2022-04-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='celenderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('catogory', models.CharField(max_length=50)),
                ('priorty', models.CharField(max_length=50)),
                ('eventTYPE', models.CharField(max_length=50)),
            ],
        ),
    ]
