# Generated by Django 4.0.2 on 2022-04-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celenderevent',
            name='event_name',
            field=models.CharField(default='Appointment <built-in function id>', max_length=100),
        ),
    ]
