# Generated by Django 4.0.2 on 2022-04-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0002_alter_celenderevent_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celenderevent',
            name='event_name',
            field=models.CharField(default='Appointment 1', max_length=100),
        ),
    ]
